### ISSUE TITLE
Permission not being requested on Android N

### ISSUE THREAD

**Issue by qswinson** [dpa99c/cordova-plugin-request-location-accuracy-example#2]
When I run this on my Android 7.0 device, I never get prompted to allow the permission. Here's the flow I'm going through in the app:

0. open app. current location mode: HIGH_ACCURACY, 'Request Location Accuracy' disabled
1. click 'Request Location Authorization'
2. dialog shows: 'Requested location authorization: authorization was NOT_REQUESTED'
3. click 'ok' on above dialog, taken back to app with no change to app UI
5. click 'Request Location Authorization'
6. dialog shows: 'Requested location authorization: authorization was 'DENIED_ALWAYS'
7. click 'ok' on above dialog, taken back to app with no change in app UI

when I go to the location settings, this app is not listed as recently requesting the location and when I look at the app info settings for the app, the UI says that no permissions were requested.

Thank you for making this project. I hope we can figure out this issue because the iPhone implementation is great. Let me know if there is anything I can do to help debug this issue. I am just getting started with cordova and Android development and I want to learn more.

**Comment by qswinson** [comment]
When I install the apk that is checked into the repo I am able to get the location from the phone successfully. Is there a modification I need to make to the AndroidManifest.xml file generated by cordova for my local build? 

This is the generated file:
```<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="20100" android:versionName="2.1.0" package="uk.co.workingedge.phonegap.plugins.example.requestlocationaccuracy" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <receiver android:name="cordova.plugins.Diagnostic$LocationProviderChangedReceiver">
            <intent-filter>
                <action android:name="android.location.PROVIDERS_CHANGED" />
            </intent-filter>
        </receiver>
        <receiver android:name="cordova.plugins.Diagnostic$NFCStateChangedReceiver">
            <intent-filter>
                <action android:name="android.nfc.action.ADAPTER_STATE_CHANGED" />
            </intent-filter>
        </receiver>
    </application>
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="25" />
</manifest>
```

**Comment by qswinson** [comment]
I solved this issue by adding the cordova-plugin-geolocation plugin to the project.

**Comment by dpa99c** [comment]
Thanks for pointing this out: you were right - there is an issue with the `config.xml` in this example: it's missing the relevant `<uses-permission/>` entries for Android. Since these are not present, they are not injected into the manifest, hence the `DENIED_ALWAYS` result. I had neglected to notice this since I also had `cordova-plugin-geolocation` present in the project, which itself [includes these](https://github.com/apache/cordova-plugin-geolocation/blob/master/plugin.xml#L40).

I'll push a commit which fixes this.
