### ISSUE TITLE
Failed to crunch

### ISSUE THREAD

**Issue by DevinCarpenter** [dpa99c/cordova-plugin-request-location-accuracy-example#3]
I've ran into an issue with building your test app, but have also solved it.

Your pathnames are very long in the app, particularly the build file pathnames generated by android. My solution was to move your test app to a very shallow location in my files like `C:/cordova-plugin-request-location-accuracy-example` in order to have it actually build correctly. It didn't take many characters being chopped off to fix it. Other than that though the app and plugin works great, so thank you.

The fix came from SO here: [https://stackoverflow.com/questions/41267005/failed-to-crunch-file-android-studio-appmergedebugresources](https://stackoverflow.com/questions/41267005/failed-to-crunch-file-android-studio-appmergedebugresources):

Here's the error in case you were wondering:

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.

>Error: Failed to crunch file C:\Users\Users\GitHub\cordova-plugin-request-location-accuracy-example\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into C:\Users\Users\GitHub\cordova-plugin-request-location-accuracy-example\platforms\android\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

**Comment by dpa99c** [comment]
The restriction of Windows path lengths to 260 characters is always a pain - I usually place all my projects in the root directory of a dedicated virtual drive to avoid these issues.
However, I noticed from some Googling that you can allegedly enable unlimited path lengths on Windows 10 - [see here](http://news.softpedia.com/news/microsoft-removes-260-characters-path-length-limit-in-windows-10-redstone-504596.shtml). I haven't tried it but it would be good to know if it works.
