### ISSUE TITLE
Install warning for play-services-base

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-request-location-accuracy-example#4]
I am upgrading my app to use Android@6.3 (from 6.2.3)  to meet the minimum requirements by Google being enforced these next two months.  When in stalling this plugin I get the following error:

C:\myapp\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\jars\classes.jar(com/google/android/gms/common/api/GoogleApiClient.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\myapp\platforms\android\src\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations
Note: Recompile with -Xlint:unchecked for details.
1 warning

Due to many errors upgrading everything at once, I am rebuilding one plugin at a time, compiling the app to ensure no errors, and then moving on to the next plugin and repeating.  This was plugin #30 that threw the first 'warning/error' - the app still compiled, but this was one of the errors I saw when upgrading everything at once (in fact, there were several of the `play-services-base\15 (or 16, or 17)` related to play services.  This is also the first plugin, via this plugin by plugin install method (as of yet) to use any google/play-services.

**Comment by dpa99c** [comment]
Did you mean to open this against [cordova-plugin-request-location-accuracy](https://github.com/dpa99c/cordova-plugin-request-location-accuracy) rather than [cordova-plugin-request-location-accuracy-example](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example)?

Seems related to the plugin rather than the example project. I'll have a look into it in the meantime...

**Comment by rolinger** [comment]
My fault, I thought I was on the cordova-plugin-request-location-accuracy.  It should be over there.  I will move it now.

**Comment by rolinger** [comment]
moved over to appropriate repository.
